name: meme_generator
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <=3.3.0' # Dart SDK version
  flutter: '>=3.16.3 <=3.19.0' # Flutter SDK version

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.0.0
  circular_menu: ^2.0.1
  dio: ^5.4.1
  image_picker: ^1.0.7
  flutter_colorpicker: ^1.0.3
  widgets_to_image: ^0.0.2
  share_plus: ^7.2.2
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
flutter:
  uses-material-design: true